version: "3.9"

services:
  eureka:
    image: 10.200.10.1:5000/demo/eureka:v1.0
    ports:
      - "8761:8761"

  provider:
    image: 10.200.10.1:5000/demo/provider:v1.0
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: "k8s"
    depends_on:
      - eureka
    command: ["/bin/sh", "-c", "until curl -f http://eureka:8761 > /dev/null ; do echo waiting for eureka; sleep 2; done; /root/app/entrypoint.sh"]
    links:
      - eureka

  sleep:
    image: curlimages/curl
    command: ["/bin/sleep", "3650d"]

  service-consumer:
    image: 10.200.10.1:5000/demo/consumer:v1.0
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: "k8s"
    depends_on:
      - eureka
    command: ["/bin/sh", "-c", "until curl -f http://eureka:8761 > /dev/null ; do echo waiting for eureka; sleep 2; done; /root/app/entrypoint.sh"]
    links:
      - eureka

  gateway:
    image: 10.200.10.1:5000/demo/gateway:v1.0
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: "k8s"
    depends_on:
      - eureka
    command: ["/bin/sh", "-c", "until curl -f http://eureka:8761 > /dev/null ; do echo waiting for eureka; sleep 2; done; /root/app/entrypoint.sh"]
    links:
      - eureka
