---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-deployment
  labels:
    app: provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider
  template:
    metadata:
      labels:
        app: provider
    spec:
      containers:
        - name: provider
          image: 10.200.10.1:5000/demo/provider:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: RUN_ARGS  # Spring Boot应用配置
              value: "--spring.profiles.active=mesh"
            - name: APP_SLEEP # 延迟启动应用5秒钟
              value: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: service-provider
spec:
  selector:
    app: provider
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: 10.200.10.1:5000/demo/consumer:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: APP_SLEEP
              value: "5"
            - name: SPRING_PROFILES_ACTIVE  # 指定激活的profile为istio
              value: "mesh"
---
apiVersion: v1
kind: Service
metadata:
  name: service-consumer
spec:
  selector:
    app: consumer
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 10.200.10.1:5000/demo/gateway:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: APP_SLEEP
              value: "5"
            - name: SPRING_PROFILES_ACTIVE  # 指定激活的profile为istio
              value: "mesh"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
