

server:
  port: 8082

spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

eureka:
  client:
    register-with-eureka: false
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: info, health, gateway

logging:
  level:
    root: INFO
    com.netflix.client: DEBUG
